# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\self_project\datn_qt\resources\uis\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setStyleSheet("background: lightblue")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_choose_file = QtWidgets.QPushButton(self.groupBox)
        self.btn_choose_file.setGeometry(QtCore.QRect(15, 30, 120, 60))
        self.btn_choose_file.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;\n"
"                color: #fff;\n"
"                border-radius: 25px;\n"
"                border: 2px solid #2980b9;\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #2980b9;\n"
"                padding-left: 15px;\n"
"                padding-top: 15px;\n"
"            }")
        self.btn_choose_file.setObjectName("btn_choose_file")
        self.btn_draw_polygon = QtWidgets.QPushButton(self.groupBox)
        self.btn_draw_polygon.setGeometry(QtCore.QRect(15, 110, 120, 60))
        self.btn_draw_polygon.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;\n"
"                color: #fff;\n"
"                border-radius: 25px;\n"
"                border: 2px solid #2980b9;\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #2980b9;\n"
"                padding-left: 15px;\n"
"                padding-top: 15px;\n"
"            }")
        self.btn_draw_polygon.setObjectName("btn_draw_polygon")
        self.btn_start = QtWidgets.QPushButton(self.groupBox)
        self.btn_start.setGeometry(QtCore.QRect(15, 190, 120, 60))
        self.btn_start.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;\n"
"                color: #fff;\n"
"                border-radius: 25px;\n"
"                border: 2px solid #2980b9;\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #2980b9;\n"
"                padding-left: 15px;\n"
"                padding-top: 15px;\n"
"            }")
        self.btn_start.setObjectName("btn_start")
        self.btn_stop = QtWidgets.QPushButton(self.groupBox)
        self.btn_stop.setGeometry(QtCore.QRect(15, 270, 120, 60))
        self.btn_stop.setStyleSheet("QPushButton {\n"
"                background-color: #3498db;\n"
"                color: #fff;\n"
"                border-radius: 25px;\n"
"                border: 2px solid #2980b9;\n"
"                font-size: 18px;\n"
"                font-weight: bold;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #2980b9;\n"
"                cursor: pointer;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #2980b9;\n"
"                padding-left: 15px;\n"
"                padding-top: 15px;\n"
"            }")
        self.btn_stop.setObjectName("btn_stop")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.groupBox_2.setStyleSheet("background: lightblue")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(60, 30, 111, 41))
        self.label_2.setStyleSheet("background: white;\n"
"border-radius: 6px;\n"
"border: 2px solid black;")
        self.label_2.setObjectName("label_2")
        self.qlabel_count_car = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_count_car.setGeometry(QtCore.QRect(230, 30, 111, 41))
        self.qlabel_count_car.setStyleSheet("background: white;\n"
"border-radius: 6px;\n"
"border: 2px solid black;")
        self.qlabel_count_car.setText("")
        self.qlabel_count_car.setObjectName("qlabel_count_car")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 111, 41))
        self.label_4.setStyleSheet("background: white;\n"
"border-radius: 6px;\n"
"border: 2px solid black;")
        self.label_4.setObjectName("label_4")
        self.qlabel_count_motor = QtWidgets.QLabel(self.groupBox_3)
        self.qlabel_count_motor.setGeometry(QtCore.QRect(230, 90, 111, 41))
        self.qlabel_count_motor.setStyleSheet("background: white;\n"
"border-radius: 6px;\n"
"border: 2px solid black;")
        self.qlabel_count_motor.setText("")
        self.qlabel_count_motor.setObjectName("qlabel_count_motor")
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.qlabel_frame = QtWidgets.QLabel(self.groupBox_2)
        self.qlabel_frame.setStyleSheet("background: black")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout_2.addWidget(self.qlabel_frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_choose_file.setText(_translate("MainWindow", "Chọn File"))
        self.btn_draw_polygon.setText(_translate("MainWindow", "Vẽ Vùng"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "Car"))
        self.label_4.setText(_translate("MainWindow", "Motor"))
        self.qlabel_frame.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
