# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\self_project\datn_qt\resources\uis\widget_draw_polygon.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDrawPolygon(object):
    def setupUi(self, WidgetDrawPolygon):
        WidgetDrawPolygon.setObjectName("WidgetDrawPolygon")
        WidgetDrawPolygon.resize(601, 368)
        self.gridLayout = QtWidgets.QGridLayout(WidgetDrawPolygon)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(WidgetDrawPolygon)
        self.groupBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.groupBox.setStyleSheet("background: lightblue")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_save = QtWidgets.QPushButton(self.groupBox)
        self.btn_save.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.btn_save.setStyleSheet("background: white;\n"
                                    "border-radius: 6px;\n"
                                    "border: 2px solid black;")
        self.btn_save.setObjectName("btn_save")
        self.btn_clear = QtWidgets.QPushButton(self.groupBox)
        self.btn_clear.setGeometry(QtCore.QRect(30, 80, 91, 31))
        self.btn_clear.setStyleSheet("background: white;\n"
                                     "border-radius: 6px;\n"
                                     "border: 2px solid black;")
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.qlabel_frame = QtWidgets.QLabel(WidgetDrawPolygon)
        self.qlabel_frame.setStyleSheet("background: black")
        self.qlabel_frame.setObjectName("qlabel_frame")
        self.gridLayout.addWidget(self.qlabel_frame, 0, 1, 1, 1)

        self.retranslateUi(WidgetDrawPolygon)
        QtCore.QMetaObject.connectSlotsByName(WidgetDrawPolygon)

    def retranslateUi(self, WidgetDrawPolygon):
        _translate = QtCore.QCoreApplication.translate
        WidgetDrawPolygon.setWindowTitle(
            _translate("WidgetDrawPolygon", "Form"))
        self.btn_save.setText(_translate("WidgetDrawPolygon", "Lưu"))
        self.btn_clear.setText(_translate("WidgetDrawPolygon", "Xóa"))
        self.qlabel_frame.setText(_translate("WidgetDrawPolygon", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDrawPolygon = QtWidgets.QWidget()
    ui = Ui_WidgetDrawPolygon()
    ui.setupUi(WidgetDrawPolygon)
    WidgetDrawPolygon.show()
    sys.exit(app.exec_())
